version: '3'

services:
  db:
    container_name: postgres_express
    image: postgres:15.1
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5433:5432

  pgadmin:
    depends_on:
      - db
    container_name: pgadmin_express
    image: dpage/pgadmin4:6.17
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PG_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PG_PASSWORD}
    ports:
      - 80:80

volumes:
  pgdata: